import os
import re
import yaml
import pandas as pd
import mysql.connector

from dotenv import load_dotenv
from google import genai
from google.genai import types


# ============================================================
# LOAD ENVIRONMENT VARIABLES
# ============================================================

load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")


# ============================================================
# GEMINI CLIENT
# ============================================================

client = genai.Client(
    api_key=GEMINI_API_KEY
)


# ============================================================
# LOAD DATABASE SCHEMA
# ============================================================

def load_schema(
    file_path="schema.yaml"
):

    with open(file_path, "r") as f:
        return yaml.safe_load(f)


DB_SCHEMA = load_schema()


# ============================================================
# SQL GENERATION PROMPT
# ============================================================
SCHEMA_PROMPT = f"""
You are an expert MySQL SQL query generator.

Your task is to convert a natural language question
into ONE valid and executable MySQL query.

DATABASE SCHEMA:
---
{yaml.dump(DB_SCHEMA, sort_keys=False)}
---

IMPORTANT DATABASE RULES:

1. Output ONLY the SQL query.
2. Do NOT output explanations.
3. Do NOT use markdown or ```sql.
4. Use ONLY the exact table names and column names
   provided in the DATABASE SCHEMA.
5. NEVER invent, modify, or guess table names.
6. NEVER append "_DATA" to a table name unless "_DATA"
   is explicitly present in the schema.
7. NEVER append "_TABLE" or "_DATA" to table names.
8. Generate MySQL-compatible SQL.
9. Use proper JOIN conditions based on the schema.
10. For "most", "highest", "top", etc.,
    use ORDER BY ... DESC and LIMIT.
11. For "least", "lowest", etc.,
    use ORDER BY ... ASC and LIMIT.
12. When calculating a metric, include the metric in SELECT
    with a meaningful alias.
13. Boolean columns such as IS_WICKET, IS_WIDE_BALL,
    IS_NO_BALL, IS_LEG_BYE, IS_BYE, IS_PENALTY and IS_SUPER_OVER
    must be compared using TRUE or FALSE without quotes.
14. Never write TRUE or FALSE as strings.
15. Before generating SQL, verify that every table and column
    used in the query exists exactly as written in the schema.

ACTUAL TABLES AVAILABLE:
- BALL_BY_BALL
- IPL_MATCHES
- PLAYERS
- TEAMS
- TEAM_ALIASES
"""


# ============================================================
# MYSQL EXECUTION
# ============================================================

def execute_sql_query(sql_query):

    if not sql_query:
        print("\n❌ SQL query is empty.")
        return None, None

    try:

        conn = mysql.connector.connect(
            host=os.getenv("MYSQL_HOST", "localhost"),
            user=os.getenv("MYSQL_USER"),
            password=os.getenv("MYSQL_PASSWORD"),
            database="IPL_ANALYTICS"
        )

        cursor = conn.cursor()

        print("\n[INFO] Executing SQL:")
        print(sql_query)

        cursor.execute(sql_query)

        rows = cursor.fetchall()

        column_names = (
            [column[0] for column in cursor.description]
            if cursor.description
            else None
        )

        cursor.close()
        conn.close()

        return rows, column_names

    except Exception as e:

        print(f"\n❌ MySQL Error: {e}")

        return None, None


# ============================================================
# CHATBOT
# ============================================================

def chatbot_main(user_query):

    print("\n" + "=" * 60)
    print(f"USER: {user_query}")
    print("=" * 60)

    try:

        # ----------------------------------------------------
        # Generate SQL using Gemini
        # ----------------------------------------------------

        response = client.models.generate_content(

            model="gemini-3.5-flash-lite",

            contents=[
                SCHEMA_PROMPT,
                f"""
Natural Language Question:

{user_query}

Generated SQL:
"""
            ],

            config=types.GenerateContentConfig(
                temperature=0.1
            )
        )

        generated_sql = response.text.strip()

        # Remove markdown wrappers if Gemini adds them
        generated_sql = re.sub(
            r"```sql\s*|\s*```",
            "",
            generated_sql,
            flags=re.IGNORECASE
        ).strip()

        # Fix common table-name mistakes generated by the LLM
        table_fixes = {
            "IPL_MATCHES_DATA": "IPL_MATCHES",
            "TEAMS_DATA": "TEAMS",
            "PLAYERS_DATA": "PLAYERS",
            "BALL_BY_BALL_DATA": "BALL_BY_BALL",
            "TEAM_ALIASES_DATA": "TEAM_ALIASES"
        }

        for wrong_name, correct_name in table_fixes.items():
            generated_sql = re.sub(
                rf"\b{wrong_name}\b",
                correct_name,
                generated_sql,
                flags=re.IGNORECASE
            )

        # Fix boolean values
        generated_sql = re.sub(
            r"IS_WICKET\s*=\s*['\"]TRUE['\"]",
            "IS_WICKET = TRUE",
            generated_sql,
            flags=re.IGNORECASE
        )

        generated_sql = re.sub(
            r"IS_WICKET\s*=\s*['\"]FALSE['\"]",
            "IS_WICKET = FALSE",
            generated_sql,
            flags=re.IGNORECASE
        )

        print("\n[DEBUG] Generated SQL:")
        print(generated_sql)

        if not generated_sql:

            print("❌ Gemini generated empty SQL.")

            return None

    except Exception as e:

        print(f"\n❌ Gemini API Error: {e}")

        return None


    # --------------------------------------------------------
    # Execute SQL
    # --------------------------------------------------------

    rows, column_names = execute_sql_query(
        generated_sql
    )


    if rows and column_names:

        df = pd.DataFrame(
            rows,
            columns=column_names
        )

        print("\n🏏 RESULT")
        print(df.to_string(index=False))

        return df

    elif rows == []:

        print("\n⚠️ Query executed but returned no results.")

        return pd.DataFrame()

    else:

        print("\n❌ Could not execute query.")

        return None


# ============================================================
# RUN CHATBOT
# ============================================================

if __name__ == "__main__":

    print("\n🏏 IPL SQL ASSISTANT")
    print("Type 'exit' to quit.")
    print("-" * 50)

    while True:

        user_query = input("\nYou: ")

        if user_query.lower() in ["exit", "quit"]:
            print("\n👋 Goodbye!")
            break

        if not user_query.strip():
            continue

        chatbot_main(user_query)